#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""DENSITY-CURVE.md -- the receipt that decides whether a close is reachable at all.

For each rung N:  S(N) = sum of 1/h over H intersect divisors(N),  NEED = 2,
slack = S - 2, |pool|, and the exact CNF size the symmetric two-halves encoding produces.
"""
from __future__ import annotations
import sys, json

sys.path.insert(0, ".")
from f273_core import in_H, divisors, factor_str, is_prime

NEED = 2.0
VAR_SOFT_CAP = 2_000_000

LADDER = [3960, 5040, 7920, 10080, 20160, 25200, 27720, 45360, 50400, 55440,
          83160, 110880, 138600, 166320, 221760, 249480, 277200, 332640,
          360360, 720720, 1441440, 2162160]

# far-field points for the ceiling statement (not encodable, listed as ceiling evidence)
FAR = [(21621600, "2^5*3^3*5^2*7*11*13"), (367567200, "2^5*3^3*5^2*7*11*13*17"),
       (6983776800, "2^5*3^3*5^2*7*11*13*17*19"),
       (160626866400, "2^5*3^3*5^2*7*11*13*17*19*23"),
       (4658179125600, "2^5*3^3*5^2*7*11*13*17*19*23*29"),
       (6064949221531200, "2^6*3^4*5^2*7^2*11*13*17*19*23*29*31"),
       (3956227026697017072000, "2^7*3^4*5^3*7^2*11*13*17*19*23*29*31*37*41*43")]


def divs_from_fact(fs):
    ds = [1]
    for part in fs.split("*"):
        if "^" in part:
            p, e = part.split("^")
            p, e = int(p), int(e)
        else:
            p, e = int(part), 1
        nd, pe = [], 1
        for _ in range(e + 1):
            nd.extend(d * pe for d in ds)
            pe *= p
        ds = nd
    return ds


def row(N):
    pool = [d for d in divisors(N) if in_H(d)]
    S = sum(1.0 / d for d in pool)
    sp = sum(pool)
    x_vars = 2 * sp                     # meaningful variables
    tot_vars = 4 * sp - len(pool)       # + Sinz at-most-one auxiliaries (exact within |pool|)
    cover_cl = 2 * N
    cover_lit = 2 * N * len(pool)
    return {"N": N, "fact": factor_str(N), "k": len(pool), "S": S,
            "slack": S - NEED, "clears": S > NEED,
            "x_vars": x_vars, "vars": tot_vars, "cover_clauses": cover_cl,
            "cover_literals": cover_lit,
            "dimacs_MB": cover_lit * 8 / 1e6,
            "encodable": S > NEED and tot_vars <= VAR_SOFT_CAP,
            "pool": pool}


def main():
    rows = [row(N) for N in LADDER]
    out = []
    W = out.append
    W("# DENSITY CURVE — Erdős 273, symmetric two-halves ladder\n")
    W("Generated by `f273_density_curve.py` (stdlib only, $0, deterministic). "
      "Question lock: `erdos273-covering-sat-ladder.json`.\n")
    W("**The quantity that decides everything.** After the parity split, Erdős 273 asks for TWO DISJOINT "
      "distinct-moduli covering systems drawn from `H = {(p−1)/2 : p prime ≥ 5}`. A distinct-moduli "
      "covering system of ℤ has `Σ 1/m > 1` **strictly** (≥ 1 by density; equality is an exact cover, "
      "impossible for ≥ 2 distinct moduli by Mirsky–Newman). So a witness with `lcm | 2N` requires\n")
    W("> **`S(N) = Σ_{h ∈ H, h | N} 1/h  >  NEED = 2`**\n")
    W("`S ≤ 2` is therefore **UNSAT by density alone — no solver is run, and none is needed.**\n")
    W("| N | factorization | \\|pool\\| | S(N) | NEED | slack S−2 | x-vars | vars (with AMO aux) | "
      "cover clauses | cover literals | DIMACS ≈ | status |")
    W("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        if not r["clears"]:
            st = "**UNSAT by density**"
        elif r["vars"] > VAR_SOFT_CAP:
            st = f"clears, but {r['vars']:,} vars > 2M soft cap"
        else:
            st = "**encodable — emitted**"
        W(f"| {r['N']:,} | `{r['fact']}` | {r['k']} | **{r['S']:.4f}** | 2 | "
          f"{r['slack']:+.4f} | {r['x_vars']:,} | {r['vars']:,} | {r['cover_clauses']:,} | "
          f"{r['cover_literals']:,} | {r['dimacs_MB']:.0f} MB | {st} |")
    W("")
    W("## The window\n")
    cl = [r for r in rows if r["clears"]]
    enc = [r for r in rows if r["encodable"]]
    W(f"* **S first clears 2 at N = {cl[0]['N']:,}** (S = {cl[0]['S']:.4f}, slack "
      f"{cl[0]['slack']:+.4f} = {cl[0]['slack']/2*100:.2f}%). Everything below it is dead by density.")
    best = max(cl, key=lambda r: r["S"])
    W(f"* **Largest slack anywhere on the ladder: N = {best['N']:,}, S = {best['S']:.4f}, "
      f"slack {best['slack']:+.4f} ({best['slack']/2*100:.2f}%)** — and that instance is "
      f"{best['vars']:,} vars / {best['dimacs_MB']:.0f} MB.")
    if enc:
        be = max(enc, key=lambda r: r["S"])
        W(f"* **Best slack inside the 2M-variable solvable window: N = {be['N']:,}, "
          f"S = {be['S']:.4f}, slack {be['slack']:+.4f} ({be['slack']/2*100:.2f}%).**")
    W("")
    W("## The ceiling — why the window never opens wide\n")
    W("`S(N)` is essentially `2·Σ_{p ≤ 2N} 1/(p−1) ≈ 2·log log N` restricted to divisors: it grows "
      "**doubly logarithmically**. Extending far past anything encodable:\n")
    W("| N | factorization | \\|pool\\| | S(N) | slack S−2 |")
    W("|---|---|---|---|---|")
    for N, fs in FAR:
        ds = divs_from_fact(fs)
        pool = [d for d in ds if in_H(d)]
        S = sum(1.0 / d for d in pool)
        W(f"| {N:,} | `{fs}` | {len(pool)} | {S:.4f} | {S-2:+.4f} |")
    W("")
    W("**Read this against the only known construction.** Selfridge's half — the `p ≥ 3` example's legal "
      "`p ≥ 5` part — runs at `Σ 1/h = 1.5556` over 11 moduli, i.e. **55.6 % slack for ONE half**. "
      "If a second, disjoint half needed comparable room, the pool would have to carry `S ≈ 3.1`. "
      "The table above says `S ≈ 2.98` at `N ≈ 4·10²¹`, and the CNF at that N is beyond astronomical. "
      "**So `S ≈ 3.1` is not reachable at any N, ever, by this route.**\n")
    W("> ### THE VERDICT THIS CURVE FORCES\n")
    W("> A witness for Erdős 273, if one exists, **cannot** resemble Selfridge's construction. It must be "
      "**far more reciprocal-efficient than any known covering system**: two disjoint halves living inside "
      "a pool with only **4–13 % total slack**, where the only comparable object in the literature uses "
      "56 % for one half. The SAT window (`27,720 ≤ N ≤ 360,360`, slack 4.4–10.6 %) is exactly where such "
      "an object would have to live, which is why every rung in it gets thrown at the solvers — but the "
      "curve is the honest statement of the odds, and of why 1980–2026 produced nothing.\n")
    W("## UNSAT provenance (recorded per rung)\n")
    W("Every ladder receipt carries `result` ∈ {`UNSAT_BY_DENSITY`, `UNSAT`, `SAT`, `UNKNOWN`}:\n")
    W("* **`UNSAT_BY_DENSITY`** — `S(N) ≤ 2`. Proved by the reciprocal-mass argument above. "
      "**No solver was invoked; `solve_seconds = 0`; no CNF exists** (the rung's `READY-N<N>.txt` says "
      "`NO-CNF reason=UNSAT_BY_DENSITY`).")
    W("* **`UNSAT`** — a solver returned exit 20 on the real CNF. This is the strong result: "
      "*no covering system of ℤ with distinct moduli `p−1` (`p ≥ 5`) has `lcm` dividing `2N`.*")
    W("* **`UNKNOWN`** — the wall-clock cap expired. `TIMEOUT_AT_N`. Establishes nothing.\n")
    W("Neither UNSAT flavour is ever a refutation of Erdős 273; both are bounded nonexistence facts "
      "with an explicit `lcm | 2N` ceiling.\n")
    txt = "\n".join(out) + "\n"
    open("DENSITY-CURVE.md", "w", encoding="utf-8", errors="replace").write(txt)
    json.dump(rows, open("density-curve.json", "w", encoding="utf-8", errors="replace"), indent=1)
    print(txt)


if __name__ == "__main__":
    main()
